//! Aider adapter — git commit attribution parser
//!
//! Aider writes attribution in git commit messages.
//! This adapter parses those messages to create TraceGit events.

use std::path::Path;

use anyhow::Result;
use regex::Regex;

use tracegit_core::adapter::{AgentAdapter, AdapterInfo, AdapterCapabilities};
use tracegit_core::schema::types::*;

/// Aider commit message patterns
const AIDER_PATTERNS: &[&str] = &[
    r"(?i)aider",
    r"(?i)AI-generated",
    r"#Aider",
    r"Co-authored-by:.*Aider",
    r"aider-chat/.*\.txt",
];

pub struct AiderAdapter {
    info: AdapterInfo,
}

impl AiderAdapter {
    pub fn new() -> Self {
        Self {
            info: AdapterInfo {
                name: "aider".to_string(),
                version: "0.1.0".to_string(),
                tool_name: "Aider".to_string(),
            },
        }
    }

    /// Check if a git commit message was generated by Aider
    pub fn is_aider_commit(message: &str) -> bool {
        AIDER_PATTERNS.iter().any(|pattern| {
            Regex::new(pattern).map(|re| re.is_match(message)).unwrap_or(false)
        })
    }

    /// Parse git log output for Aider commits
    pub fn parse_git_log(
        &self,
        repo_root: &Path,
        since: &str,
    ) -> Result<Vec<TraceEvent>> {
        let output = std::process::Command::new("git")
            .args([
                "log",
                &format!("--since={}", since),
                "--pretty=format:%H%n%s%n%b%n---END---",
                "--name-status",
            ])
            .current_dir(repo_root)
            .output()?;

        if !output.status.success() {
            return Ok(Vec::new());
        }

        let stdout = String::from_utf8_lossy(&output.stdout);
        let mut events = Vec::new();

        for commit_block in stdout.split("---END---") {
            let lines: Vec<&str> = commit_block.lines().collect();
            if lines.len() < 3 {
                continue;
            }

            let commit_sha = lines[0].trim();
            let subject = lines.get(1).map(|s| s.trim()).unwrap_or("");
            let body: String = lines[2..].join("\n");
            let full_message = format!("{}\n{}", subject, body);

            if !Self::is_aider_commit(&full_message) {
                continue;
            }

            // Parse changed files from name-status lines
            for line in &lines[2..] {
                let parts: Vec<&str> = line.splitn(2, char::is_whitespace).collect();
                if parts.len() < 2 {
                    continue;
                }

                let status = parts[0].trim();
                let file_path = parts[1].trim();

                let event_type = match status.chars().next() {
                    Some('A') => EventType::FileWrite,
                    Some('D') => EventType::FileDelete,
                    _ => EventType::FileWrite,
                };

                events.push(TraceEvent {
                    schema: "tracegit.event.v1".to_string(),
                    id: tracegit_core::schema::ids::generate_event_id(),
                    session_id: format!("aider-{}", &commit_sha[..8]),
                    timestamp: chrono::Utc::now().to_rfc3339(),
                    event_type,
                    actor: EventActor::Agent,
                    payload: serde_json::json!({
                        "git_commit_sha": commit_sha,
                        "commit_message": subject,
                        "file_path": file_path,
                        "change_type": status,
                        "tool": "aider",
                    }),
                    redaction: None,
                    prev_hash: None,
                    event_hash: None,
                });
            }
        }

        Ok(events)
    }
}

#[async_trait::async_trait]
impl AgentAdapter for AiderAdapter {
    fn info(&self) -> &AdapterInfo {
        &self.info
    }

    fn capabilities(&self) -> AdapterCapabilities {
        AdapterCapabilities {
            can_capture_file_writes: true,
            can_capture_commands: false,
            can_capture_prompts: false,
            can_replay_session: false,
            supports_hooks: false,
        }
    }

    async fn start_session(&self, session: &Session) -> Result<String> {
        Ok(session.id.clone())
    }

    async fn end_session(&self, session_id: &str) -> Result<()> {
        Ok(())
    }

    async fn capture_event(&self, event: &TraceEvent) -> Result<()> {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_adapter_info() {
        let adapter = AiderAdapter::new();
        assert_eq!(adapter.info().name, "aider");
        assert!(adapter.capabilities().can_capture_file_writes);
        assert!(!adapter.capabilities().supports_hooks);
    }

    #[test]
    fn test_is_aider_commit() {
        assert!(AiderAdapter::is_aider_commit("feat: add auth module\n\n#Aider"));
        assert!(AiderAdapter::is_aider_commit("AI-generated code for login flow"));
        assert!(AiderAdapter::is_aider_commit("fix: typo\n\nCo-authored-by: Aider <aider@aider.chat>"));
        assert!(!AiderAdapter::is_aider_commit("fix: typo in readme"));
    }
}
